# rolebinding.yml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rolebinding_name
  namespace: rolebinding_namespace
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: rolebinding_role_name
subjects:
  - kind: ServiceAccount
    name: service_account_name
    namespace: rolebinding_sa_namespace